apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-rollupdate
  namespace: test-namespace
  labels:
    app: testing
spec:
  replicas: 3
  strategy:
    type: RollingUpdate  # by default strategy if not mentioned.
    rollingUpdate:
      maxUnavailable: 1  # maximum number of Pods that can be unavailable during the update process.
      maxSurge: 2        # maximum number of Pods that can be created over the desired number of Pods.
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: testing
        image: bitbull/webserver


