apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: test-namespace
data:
  username: aW1ncm9vdAo=
  password: aW1ncm9vdDEwCg==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-deploy
  namespace: test-namespace
  labels:
    app: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: testing
        image: bitbull/webserver
        ports:
        - containerPort: 80
        env:
        - name: user
          valueFrom:
            secretKeyRef:
              name: secret
              key:  username
